# NumPy

### NumPy is an open-source software library that enables high-performance numerical computing in Python. Created in 2005 from the Numeric and Numarray projects, it is the foundation of the scientific Python ecosystem, powering libraries such as SciPy, pandas, and scikit-learn. NumPy provides efficient N-dimensional arrays, mathematical functions, and tools that combine the simplicity of Python with the speed of compiled C code.

In [4]:
# Array

import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [10]:
# Basic operations

print(arr + 2)
print(arr * 2)
print(arr / 2)

[3 4 5 6 7]
[ 2  4  6  8 10]
[0.5 1.  1.5 2.  2.5]


In [13]:
# 2D array

matrix = np.array([
    [1, 2],
    [3, 4]
])
print(matrix)
print(matrix + 2)

[[1 2]
 [3 4]]
[[3 4]
 [5 6]]
